service:
    # If you don't have a mailcatcher set up, set the role of this service to mail. Mails will not work then, but
    # you won't get an error on start:
    #roles:
    #  - mail

    # If this is your main PHP service, add the role 'php'. You can then use the from-service php command template.
    #roles:
    #  - php

    image: riptidepy/php
    environment:
      XDEBUG_CONFIG: 'remote_host={{ host_address() }}'
      PHP_IDE_CONFIG: 'serverName=riptide-{{ parent().parent().name }}'
    config:
      php_ini:
        from: assets/php.ini
        # w to load before xdebug.ini
        to: '/usr/local/etc/php/conf.d/w_riptide.ini'
      xdebug_ini:
        from: assets/xdebug.ini
        to: '/usr/local/etc/php/conf.d/xdebug.ini'
        force_recreate: true
      msmtprc:
        from: assets/msmtprc
        to: '/etc/msmtprc'
    additional_volumes:
      opcache:
        host: "~/.php_riptide_opcache/xdebug_{% if system_config().get_plugin_flag('php-xdebug.enabled') %}enabled{% else %}disabled{% endif %}"
        container: "/opcache"
