app:
  name: jupyter

  notices:
    usage: >-
      After starting the service, you can open Jupyter in the browser.
    installation: >-
      Run riptide start, then check JUPYTER.md.

  services:
    jupyter:
      $ref: /service/jupyter/base

  commands:
    python:
      $ref: /command/python/in-python-service
    pip:
      $ref: /command/pip/in-python-service
    jupyter:
      # -i for interactive shell, so .bashrc is read
      command: bash -i -c "jupyter \"\$@\"" --
      in_service_with_role: python
    poetry:
      $ref: /command/poetry/in-python-service
