service:
  image: riptidepy/shopify:latest
  command:
    default: 'sleep 3'
    keep_running: '$(while true; do sleep 1; done)'
  roles:
    - main
    - shopify
    - src
  additional_volumes:
    composer_config:
      container: /home/riptide/.config/composer
      host: ~/.config/composer
    composer_cache:
      container: /home/riptide/.cache/composer
      host: ~/.cache/composer
    cargo_cache:
      container: /home/riptide/.cache/cargo
      host: ~/.cache/cargo
    shopify_config:
      container: /home/riptide/.config/shopify
      host: ~/.config/shopify
    shopify_config_cli_kit_nodejs:
      container: /home/riptide/.config/shopify-cli-kit-nodejs
      host: ~/.config/shopify-cli-kit-nodejs
    shopify_config_cli_app_nodejs:
      container: /home/riptide/.config/shopify-cli-app-nodejs
      host: ~/.config/shopify-cli-app-nodejs
    shopify_cache_cli_nodejs:
      container: /home/riptide/.cache/shopify-cli-nodejs
      host: ~/.cache/shopify-cli-nodejs
    shopify_cache:
      container: /home/riptide/.cache/shopify
      host: ~/.cache/shopify
    shopify_cache_at:
      container: /home/riptide/.cache/@shopify
      host: ~/.cache/@shopify
    shopify_cache_gems_nodejs:
      container: /home/riptide/.cache/shopify-gems-nodejs
      host: ~/.cache/shopify-gems-nodejs
    ngrok_config:
      container: /home/riptide/.config/ngrok
      host: ~/.config/ngrok
    yarn_cache:
      container: /home/riptide/.cache/yarn
      host: ~/.cache/yarn
    npm_cache:
      container: /home/riptide/.npm
      host: ~/.npm
    ssh:
      container: /home/riptide/.ssh
      host: ~/.ssh
      mode: ro
    tmp:
      container: /tmp/
      host: '{{ get_tempdir() }}'
  working_directory: .
  logging:
    stdout: true
    stderr: true
