app:
  name: shopify

  notices:
    usage: >-
      Don't start the Shopify service, it will stop automatically. Use the Riptide commands, like described in the shopify-app.md.
      The commands won't work properly, if you have the service running.
      If you really want the container to keep running, e.g. to jump into it, use "riptide start -c keep_running".
    installation: >-
      Run riptide cmd setup, then check shopify-app.md for further steps.

  services:
    shopify:
      $ref: /service/shopify/base
      roles:
        - main
        - node

  commands:
    shopify:
      command: bash -c "cd /src && ./node_modules/.bin/shopify \"\$@\"" --
      use_host_network: true
      in_service_with_role: shopify
    npm:
      $ref: /command/npm/in-node-service
    yarn:
      $ref: /command/yarn/in-node-service
    node:
      $ref: /command/node/in-node-service
    composer:
      command: bash -c "cd /src/web && composer \"\$@\"" --
      use_host_network: true
      in_service_with_role: shopify
    artisan:
      command: bash -c "cd /src/web && ./artisan \"\$@\"" --
      use_host_network: true
      in_service_with_role: shopify
    setup:
      command: echo Setup done! Please check shopify-app.md.
      in_service_with_role: shopify
