command:
    image: riptidepy/php
    command: php
    environment:
      PHP_IDE_CONFIG: 'serverName=riptide-{{ parent().parent().name }}'
    additional_volumes:
      opcache:
        host: "~/.cache/riptide/{{ parent().parent().name }}/{{ image }}/opcache/xdebug_{% if system_config().get_plugin_flag('php-xdebug.enabled') %}en{% else %}dis{% endif %}abled"
        container: "/opcache"
        volume_name: "php_opcache__{{ parent().parent().name }}__{{ image | replace(':', '_') | replace('/', '_') }}__xdebug_{% if system_config().get_plugin_flag('php-xdebug.enabled') %}enabled{% else %}disabled{% endif %}"
      tmp_phpinfo:
        host: "{{ get_tempdir() }}/ide-phpinfo.php"
        container: "{{ get_tempdir() }}/ide-phpinfo.php"
      tmp_phpinfo_macos:
        host: "/private{{ get_tempdir() }}/ide-phpinfo.php"
        container: "/private{{ get_tempdir() }}/ide-phpinfo.php"
        host_system: Darwin