service:
  image: riptidepy/keycloak:latest
  port: 8080
  command: "start-dev"
  environment:
    KC_FEATURES: "account-api,account2,account3,admin-api,admin-fine-grained-authz,admin2,authorization,ciba,client-policies,client-secret-rotation,declarative-user-profile,docker,impersonation,par,preview,recovery-codes,scripts,step-up-authentication,token-exchange,update-email"
    KEYCLOAK_ADMIN: "admin"
    KEYCLOAK_ADMIN_PASSWORD: "admin"
  logging:
    stdout: true
    stderr: true
