command:
  image: 'riptidepy/php:7.3-cli'  # Use 'composer' instead for up to date composer (but without any PHP extensions)
  command: "php -dmemory_limit=-1 $(which composer)"
  additional_volumes:
    tmp:
      host: '{{ get_tempdir() }}'
      container: '/tmp/'
      volume_name: 'tmp'
  environment:
    COMPOSER_HOME: '{{ home_path() }}/.composer'
