app:
  name: streamlit

  notices:
    usage: >-
      After starting the service, you can open Streamlit in the browser.
    installation: >-
      Run riptide start, then check STREAMLIT.md.

  services:
    streamlit:
      $ref: /service/streamlit/base
      roles:
        - main
        - python

  commands:
    python:
      $ref: /command/python/in-python-service
    pip:
      $ref: /command/pip/in-python-service
    streamlit:
      # -i for interactive shell, so .bashrc is read
      command: bash -i -c "streamlit \"\$@\"" --
      in_service_with_role: python
    poetry:
      $ref: /command/poetry/in-python-service
